# -*- coding: utf-8 -*-
"""Renewable-Diffusion-Network-Bar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u5JIj-NPtZ_HYy_HNWdItRTVTAxRyJFm
"""

import pandas as pd
import os
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
from random import sample
from itertools import chain 
import csv
import glob
import os
from numpy.random import poisson #import
import pickle
import scipy
from scipy import stats
from functools import reduce

#https://www.delftstack.com/howto/matplotlib/how-to-set-tick-labels-font-size-in-matplotlib/#ax.set_xticklabelsxlabels-fontsize-to-set-matplotlib-tick-labels-font-size
# https://stackoverflow.com/questions/29498652/plot-bar-graph-from-pandas-dataframe

output = pd.read_csv('/content/drive/MyDrive/G11-MEA-Diffusion/dataRE_REN/REN_v4.3_5352_master.csv')

crosstab = output.groupby(['year'])['sum'].mean().reset_index()

#fig.set_size_inches(18.5, 10.5)
ax = crosstab.plot.bar(x='year', y='sum', rot=0, figsize=(12, 9), legend=False)
plt.xlabel('Year', fontsize=15)
plt.ylabel('Average Number of Renewable Energy Policies per Country', fontsize=15)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.savefig("bargraph1.png")
plt.show()

crosstab2 = output.groupby(['year', 'inc_classification'])['sum'].mean().reset_index()
crosstab2 = crosstab2.rename(columns={"inc_classification": "Country Classifications by Income Level"}, errors="raise")
crosstab2['Country Classifications by Income Level'] = crosstab2['Country Classifications by Income Level'].replace(to_replace =1, value ="Low-Income Countries (GDP Per Capita Under \$4,000)")
crosstab2['Country Classifications by Income Level'] = crosstab2['Country Classifications by Income Level'].replace(to_replace =2, value ="Mid-Income Countries (GDP Per Capita \$4,000 – \$12,000)")
crosstab2['Country Classifications by Income Level'] = crosstab2['Country Classifications by Income Level'].replace(to_replace =3, value ="High-Income Countries (GDP Per Capita Over \$12,000)")

crstab2_long = crosstab2.pivot_table(index=["year"], 
                    columns='Country Classifications by Income Level', 
                    values='sum')

ax2 = crstab2_long[["Low-Income Countries (GDP Per Capita Under \$4,000)", "Mid-Income Countries (GDP Per Capita \$4,000 – \$12,000)", "High-Income Countries (GDP Per Capita Over \$12,000)"]].plot(kind='bar', figsize=(12, 9), legend=True)
ax2.set_xlabel("Year", fontsize=15)
ax2.set_ylabel("Average Number of Renewable Energy Policies per Country", fontsize=15)
plt.legend(fontsize=15) 
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.savefig("bargraph2.png")
plt.show()